apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: b7e73159-417e-4a6a-93e8-4aed9420b409
    keyvaultName: fortress-inquisitorious      
    cloudName: ""  
    objects:  |
      array:
        - |
          objectName: sqlServer
          objectType: secret             
          objectVersion: ""      
        - |
          objectName: sqlUser
          objectType: secret             
          objectVersion: ""
        - |
          objectName: sqlPassword
          objectType: secret             
          objectVersion: ""
    tenantId: 48ce9607-8734-43af-b123-8ff166460191                