apiVersion: apps/v1
kind: Deployment
metadata:
    name: tripviewer-deployment
    labels:
        app: tripviewer
spec:
    replicas: 3
    selector:
        matchLabels:
          app: tripviewer
    template:
        metadata: 
            labels: 
                app: tripviewer
        spec:
            containers:
            -   image: registrymsd2910.azurecr.io/tripinsights/tripviewer:1.0
                name: tripviewer
                ports:
                - containerPort: 80
                  name: tv-web-svc
                env:
                    - name: TRIPS_API_ENDPOINT
                      value: http://trips-service:80
                    - name: USERPROFILE_API_ENDPOINT
                      value: http://userprofile-service:80
                    - name: ASPNETCORE_ENVIRONMENT
                      value: Development
                    - name: HTTP_PROXY
                      value: ''
                    - name: http_proxy
                      value: ''
                    - name: HTTPS_PROXY
                      value: ''
                    - name: https_proxy
                      value: ''
            imagePullSecrets:
            - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  selector:
    app: tripviewer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

  
