apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-java-deployment
    labels:
        app: user-java
spec:
    replicas: 3
    selector:
        matchLabels:
          app: user-java
    template:
        metadata: 
            labels: 
                app: user-java
        spec:
            containers:
            -   image: registrymsd2910.azurecr.io/tripinsights/user-java:1.0
                name: user-java
                ports:
                - containerPort: 80
                  name: user-web-svc
                env:
                 - name: SQL_SERVER
                   valueFrom:
                    secretKeyRef:
                      name: sql-connection
                      key: SQL_SERVER
                 - name: SQL_USER
                   valueFrom:
                    secretKeyRef:
                      name: sql-connection
                      key: SQL_USER
                 - name: SQL_PASSWORD
                   valueFrom:
                    secretKeyRef:
                      name: sql-connection
                      key: SQL_PASSWORD
            imagePullSecrets:
            - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: user-web-svc