apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-java-deployment
    namespace: api-dev
    labels:
        app: user-java
spec:
    replicas: 3
    selector:
        matchLabels:
          app: user-java
    template:
        metadata: 
            labels: 
                app: user-java
        spec:
            containers:
            -   image: registrymsd2910.azurecr.io/tripinsights/user-java:1.0
                name: user-java
                ports:
                - containerPort: 80
                  name: user-web-svc
                volumeMounts:
                  - name: secrets-store01-inline
                    mountPath: "/mnt/secrets-store"
                    readOnly: true
                env:
                    - name: SQL_SERVER
                      valueFrom:
                        secretKeyRef:
                            name: secrets-store01-inline
                            key: sqlServer
                    - name: SQL_USER
                      valueFrom:
                        secretKeyRef:
                            name: secrets-store01-inline
                            key: sqlUser
                    - name: SQL_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: secrets-store01-inline
                            key: sqlPassword
            imagePullSecrets:
            - name: regcred
            volumes:
            - name: secrets-store01-inline
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                    secretProviderClass: "azure-kvname-user-msi"
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
  namespace: api-dev
spec:
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: user-web-svc