apiVersion: apps/v1
kind: Deployment
metadata:
    name: userprofile-deployment
    namespace: api-dev
    labels:
      app: userprofile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      imagePullSecrets: 
      - name: regcred
      containers:
      - image: registrymsd2910.azurecr.io/tripinsights/userprofile:1.0
        name: userprofile
        ports:
        - containerPort: 80
          name: profile-web-svc
        env:
            - name: SQL_SERVER
              valueFrom:
                 secretKeyRef:
                    name: sql-connection
                    key: SQL_SERVER
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                    name: sql-connection
                    key: SQL_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: sql-connection
                    key: SQL_PASSWORD
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile-service
  namespace: api-dev
spec:
  selector:
    app: userprofile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
